### ISSUE TITLE
Create/Edit Sample Set - Associated data inputs don't auto select

### ISSUE THREAD

**Issue by beforan** [biobankinguk/biobankinguk#583]
Prior to v4.x, When creating or editing a sample set, you could click on the timeframe radio buttons and it would auto check that row's checkbox.

In v4.x that doesn't work, and it should.

I'm also 90% sure checked rows used to highlight green, and they don't currently.

I assume some JS either isn't loading or isn't working right anymore.

**Comment by blargly** [comment]
This problem actually occurs when also creating a collection with the associated data, so looks like a common problem.

**Comment by blargly** [comment]
Completed. Pull request: https://github.com/biobankinguk/biobankinguk/pull/592
