### ISSUE TITLE
🐛 Possible missing favicon in v4.x

### ISSUE THREAD

**Issue by beforan** [biobankinguk/biobankinguk#587]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Favicon is empty or adopts a cached icon (such as Microsoft's from the Azure landing page when deployed)

![image](https://github.com/biobankinguk/biobankinguk/assets/1846005/2632d080-7df7-4df9-af42-e38cb2ad4bb2)

### Expected Behavior

Favicon should match that of the docs site

![image](https://github.com/biobankinguk/biobankinguk/assets/1846005/c1d373d9-32f2-49aa-9827-bb8519004282)

### Steps To Reproduce

1. Open a browser
2. Navigate to the dev site https://dev.directory.biobankinguk.org 
3. Observe an incorrect favicon

### Environment

```markdown
- OS: macOS Sonoma 14.2.1
- Browser: Edge 120.0.2210.144 (Official build) (arm64)
```

### Anything else?

I've not yet checked the codebase to see if the favicon was wrongly implemented, or not implemented.

**Comment by AndyRae** [comment]
This should be implemented in the Azure pipeline to override it, as it is environment specific.
