### ISSUE TITLE
Registering more than one biobank to an account

### ISSUE THREAD

**Issue by prquinlan** [biobankinguk/biobankinguk#599]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When you are a user that has an existing biobank but then register a new one, it sends the email to you ok, but then when you try and click the link, it fails to take you to the registration page and gives you an error stating "Access to the requested page was denied". 

### Expected Behavior

It would let you register the new biobank

### Steps To Reproduce

1) Have an account with a biobank already registered 
2) register a new biobank
3) admin approves registration
4) click on link sent in email 
5) it then fails 

### Environment

```markdown
- OS:
- Other environment details:
```

**Comment by AndyRae** [comment]
I can recreate this. Looks like the link goes to: `/Profile/Create/3?Area=Biobank&newBiobank=True`

I can't remember the intended workflow here, so will investigate where this should be directing to.
